spring:
  datasource:
    url: jdbc:postgresql://localhost:35432/dogs
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  main:
    allow-circular-references: true

remote:
  breed_url: https://dog.ceo/api/breeds/list/all