#spring:
#  profiles:
#    active: prod

#logging:
#  level:
#    org.springframework.transaction: debug
#    org.springframework.orm.jpa: debug
#    org.hibernate.cache: DEBUG
spring:
  datasource:
    url: jdbc:postgresql://localhost:35432/dogs
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        cache:
          use_second_level_cache: true
          region:
            factory_class: org.hibernate.cache.jcache.internal.JCacheRegionFactory
          use_query_cache: true
        hbm2ddl:
          auto: create-drop
    show-sql: true

  main:
    allow-circular-references: true


remote:
  breed_url: https://dog.ceo/api/breeds/list/all
